name: Print file from a release tag
on:
  workflow_dispatch:
jobs:
  print-file:
    name: Get latest file and print
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Required due to the way Git works, without it this action won't be able to find any or the correct tags
      - name: "Get latest tag"
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"

      - name: print tag
        run: echo "${{ steps.previoustag.outputs.tag }}"

      - name: saving first xml file
        run: git show ${{ steps.previoustag.outputs.tag }}:app/src/main/res/values/strings.xml > tag_strings.xml

      - name: adding permission to sorting script
        run: chmod +x .github/workflows/scripts/sort_xml.sh
        shell: bash

      - name: sorting first file
        run: .github/workflows/scripts/sort_xml.sh .github/workflows/scripts/tag_strings.xml
        shell: bash

      # second file

      - name: saving second xml file
        run: git show ${{ steps.previoustag.outputs.tag }}:app/src/main/res/values/strings.xml > branch_strings.xml

      - name: sorting second file
        run: .github/workflows/scripts/sort_xml.sh .github/workflows/scripts/branch_strings.xml
        shell: bash



#        run: git diff ${{steps.tag.outputs.tag}} dev --app/src/main/res/values/strings.xml
