name: Print file from a release tag
on:
  workflow_dispatch:
jobs:
  print-file:
    name: Get latest file and print
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Required due to the way Git works, without it this action won't be able to find any or the correct tags
      - name: "Get latest tag"
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"

      - name: print tag
        run: echo ${{steps.tag.outputs.tag}}