name: Run tests

on:
  push:
  workflow_dispatch:

jobs:
  test:
    name: Setup and run test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Unit Test
        uses: gradle/gradle-build-action@v2
        with:
          arguments: testReleaseUnitTest